services:
  db:
    image: mariadb:11.4.5  #não pode ser uma versão maior do que 11.05.xx
    container_name: zabbix-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-trunk
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    depends_on:
      - db
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-trunk
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: LOPES SUPERMERCADOS
    depends_on:
      - db
      - zabbix-server
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./certs:/etc/ssl/certs
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge
